obj-m := first_module.o
obj-m += kernel_module_init.o
obj-m += kernel_module_exit.o

obj-m := kernel_module_init_exit.o
kernel_module_init_exit-objs := kernel_module_init.o kernel_module_exit.o

obj-m := first_module.o
obj-m += optimized_first_module.o
